### ISSUE TITLE
UI demo server odd display

### ISSUE THREAD

**Issue by zcstarr** [attic-labs/noms#2700] opened 2016-10-13 00:18 UTC
The UI is truncating the photos that should be displayed in the photos index

**Comment by zcstarr** [comment] 2016-10-13 00:30
I'm getting some strange behavior with the results from the photo indexer in the UI. 

The dataset in question is : 
http://photos.noms.io/?index=http://demo.noms.io/zane::#egr1b176tt6i08m175dfnpoguvc4vm9d.value

Some special things to note here , is that the name field for the faces rect, is empty string, perhaps this is causing some ui mayhem ? We expect regardless of this to see 10 photos ? 

Any thoughts ?

**Comment by kalman** [comment] 2016-10-18 23:29
It's because there are only 4 different timestamps, so the UI is coalescing (de-duping) those photos. Were these photos from Facebook, in which case it could be https://github.com/attic-labs/noms/issues/2723?

**Comment by aboodman** [comment] 2016-10-18 23:35
Dupe of #2723

**Closed by aboodman** 2016-10-18 23:35 UTC
