### ISSUE TITLE
fb/slurp and flickr/slurp regularly conflicting on demo-server

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2699] opened 2016-10-12 23:12 UTC
If you look at the logs you see the following almost every run:

```
Cronic detected failure or error output for the command:
node /home/ec2-user/js/fb/slurp ...

RESULT CODE: 1

ERROR OUTPUT:
[Error: HTTP Error: 409]

STANDARD OUTPUT:
[2K
0% photos of 90 imported...[2K
100% photos of 90 imported...
```

It's either the fb or flickr importer everytime that conflicts. These two are (purposely) running concurrently. They should auto-resolve, right?

**Comment by aboodman** [comment] 2016-10-12 23:58
I tried to simulate this quickly by adding a `wait()` to one of them then letting the other commit, but it didn't happen.

**Comment by cmasone-attic** [comment] 2016-10-13 00:02
Is there any way to test this without a facebook acct? Can you get a more
tractable reproduction?

**Comment by aboodman** [comment] 2016-10-13 00:03
I'll think about how to do that.

**Comment by aboodman** [comment] 2016-10-14 16:59
I hacked up this quick patch that theoretically should fix the problem: https://github.com/attic-labs/noms/pull/2708. Feel free to take it over.

But I was not able to reproduce the bug because of a different bug: https://github.com/attic-labs/noms/issues/2707

I think that once #2707 is fixed, then if you run the modified counter in https://github.com/attic-labs/noms/pull/2706 against two _different_ datasets then it will simulate the bug I was reporting here. Then you can use my patch and see if it fixes it.

**Comment by cmasone-attic** [comment] 2016-10-14 18:50
I took out the check I mentioned in #2707, artificially causing that case to be a failure.

I re-ran your test here and everything succeeded, which i believe should be expected based on the code:
```js
  async _doCommit(datasetId: string, commit: Commit<any>): Promise<Ref<any>> {
    const commitRef = this.writeValue(commit);

    for (;;) {
      const currentRootRefP = this._rt.getRoot();
      const currentRootRef = await currentRootRefP;
      let currentDatasets = await this._datasetsFromRootRef(currentRootRefP);
      if (!currentRootRef.isEmpty()) {
        const currentHeadRef = await currentDatasets.get(datasetId);
        if (currentHeadRef) {
          // if (equals(commitRef, currentHeadRef)) {
          //   break;
          // }
          if (!await this._descendsFrom(commit, currentHeadRef)) {
            throw new Error('Merge needed');
          }
        }
      }

      currentDatasets = await currentDatasets.set(datasetId, commitRef);
      const newRootRef = this.writeValue(currentDatasets).targetHash;
      if (await this._rt.updateRoot(newRootRef, currentRootRef)) {
        break;
      }
    }
    return commitRef;
  }
```

At the beginning of each run through the `for` loop, the code gets the current Root of the Database and loads the Map<string, Ref<Commit>> that it points to. This means that, the code will see if commits that landed since last time the code loaded this map. In the test you're running with two interleaved counters running against different datasets, whichever one goes to commit second will (usually) do so after the first has completed its work. So, it begins committing, loads the new Root, and determines that it's able to land its commit without conflict.

I think the only actual problem here is the bad handling of the 409

**Comment by aboodman** [comment] 2016-10-14 20:19
I can't think of a good way to reproduce this other than just racing two javascript programs that commit to different datasets on  same db.

I think it would be sufficient though to write a unit test that returns 409 and go from there.

**Comment by cmasone-attic** [comment] 2016-10-14 20:29
I wrote a unit test that (is supposed to) simulate this race and ensure it's handled correctly. It fakes things out at the batch store level, cutting HTTP out of the loop, so it didn't catch the 409 problem.  It's called "commit with concurrent chunk store use" in database-test.js...It sounds like you looked at that and don't think it correctly tests the commit logic?

**Comment by aboodman** [comment] 2016-10-14 20:30
I did see that. I agree that writing a unit test that mocks the http server and tests this one change would be great. I'm not sure it will fix the actual bug I'm seeing, but I hope it does.

**Closed** 2016-10-17 18:53 UTC
